# Consulta los 4 servicios Cloud Run y escribe sus URLs en .env.cloud.
#
# Uso:
#   .\scripts\dump_mcp_urls.ps1            # escribe .env.cloud
#   .\scripts\dump_mcp_urls.ps1 -Apply     # además exporta las vars en la sesión actual

param(
    [switch]$Apply
)

$ErrorActionPreference = "Stop"

$PROJECT = "decomind-agent-challenge"
$REGION  = "europe-west1"

$services = @(
    @{ env = "MCP_GEOCODING_URL";        name = "mcp-geocoding" }
    @{ env = "MCP_MARKET_RESEARCH_URL";  name = "mcp-market-research" }
    @{ env = "MCP_RENOVATION_URL";       name = "mcp-renovation" }
    @{ env = "MCP_DOSSIER_PDF_URL";      name = "mcp-dossier-pdf" }
    @{ env = "MCP_CATASTRO_URL";         name = "mcp-catastro" }
    @{ env = "MCP_NOTARIADO_URL";        name = "mcp-notariado" }
)

$lines = @("# Generated by scripts/dump_mcp_urls.ps1 - do not edit by hand.")

foreach ($svc in $services) {
    $url = & gcloud run services describe $svc.name `
        --region $REGION --project $PROJECT --format "value(status.url)"
    if (-not $url) {
        Write-Host "WARN: $($svc.name) no encontrado" -ForegroundColor Yellow
        continue
    }
    $line = "$($svc.env)=$url"
    $lines += $line
    Write-Host $line

    if ($Apply) {
        Set-Item -Path "env:$($svc.env)" -Value $url
    }
}

$lines | Out-File -FilePath ".env.cloud" -Encoding utf8
Write-Host ""
Write-Host ".env.cloud actualizado." -ForegroundColor Green

if ($Apply) {
    Write-Host "Variables exportadas en la sesión actual." -ForegroundColor Green
} else {
    Write-Host "Para cargarlas en la sesión:" -ForegroundColor Yellow
    Write-Host "  .\scripts\dump_mcp_urls.ps1 -Apply"
}
